name: Docker Image CI

on:
  workflow_dispatch:   

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Run a one-line script
      run: docker run --rm mcr.microsoft.com/dotnet/framework/samples:dotnetapp